# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=25)),
                ('last_name', models.CharField(help_text='Last Name', max_length=40)),
                ('email_id', models.CharField(help_text='Email Id', max_length=100)),
                ('mobile', models.CharField(help_text='Mobile Number', max_length=13)),
                ('age', models.IntegerField(help_text='Age')),
                ('date_of_birth', models.DateField()),
                ('place', models.CharField(help_text='Place', max_length=1000)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
