# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20170610_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.CharField(help_text='Age', max_length=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.CharField(help_text='dob', max_length=30),
        ),
    ]
