# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20170611_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(help_text='Mobile Number', max_length=10),
        ),
    ]
